<a href="https://colab.research.google.com/github/chineidu/NLP-Tutorial/blob/main/notebook/03_tensorflow/01_intro_to_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Tutorial

In [1]:
!pip install nb_black

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
# Standard imports
import numpy as np
import tensorflow as tf

# Black code formatter (Optional)
# %load_ext lab_black
%load_ext nb_black

<IPython.core.display.Javascript object>

* Intro To Tensors
* Getting info from tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function
* Using GPUs/TPUs with TensorFlow


In [3]:
tf.__version__

'2.11.0'

<IPython.core.display.Javascript object>

In [4]:
!python -V

Python 3.8.10


<IPython.core.display.Javascript object>

### Create Tensors

In [5]:
# tf.constant
tensor_1 = tf.constant([1,2,3,4]) # Vector
tensor_1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

<IPython.core.display.Javascript object>

In [6]:
tensor_1.shape, tensor_1.ndim

(TensorShape([4]), 1)

<IPython.core.display.Javascript object>

In [7]:
tensor_2 = tf.constant([[1,2,3,4], [5,6,7,8]], dtype=tf.float16) # Matrix
tensor_2, tensor_2.shape, tensor_2.ndim

(<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
 array([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], dtype=float16)>, TensorShape([2, 4]), 2)

<IPython.core.display.Javascript object>

In [8]:
tensor_3 = tf.constant([[[1,2,3], [4,5,6], [7, 8, 9]]], dtype=tf.float16) # Tensor
tensor_3

<tf.Tensor: shape=(1, 3, 3), dtype=float16, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float16)>

<IPython.core.display.Javascript object>

In [9]:
tensor_3.shape, tensor_3.ndim

(TensorShape([1, 3, 3]), 3)

<IPython.core.display.Javascript object>

In [10]:
tensor_4 = tf.constant([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17, 18]]])
tensor_4

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

<IPython.core.display.Javascript object>

### Creating Tensors Using tf.Variable

In [11]:
# tf.constant
changeable_tensor_1 = tf.Variable([1,2,3,4]) # Vector
changeable_tensor_1

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

<IPython.core.display.Javascript object>

In [12]:
# Change an element in the tensor (Only possible for tensors created using tf.Variable)
changeable_tensor_1[0].assign(-2)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([-2,  2,  3,  4], dtype=int32)>

<IPython.core.display.Javascript object>

In [13]:
 changeable_tensor_1

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([-2,  2,  3,  4], dtype=int32)>

<IPython.core.display.Javascript object>

### Creating Random Tensors

In [14]:
RANDOM_STATE = 123
rng = tf.random.Generator.from_seed(RANDOM_STATE)

random_tensor_1 = rng.uniform(shape=(2, 2), dtype=tf.float16)
random_tensor_1

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[0.8076, 0.793 ],
       [0.4648, 0.2275]], dtype=float16)>

<IPython.core.display.Javascript object>

In [15]:
random_tensor_2 = rng.normal(shape=(2,2))
random_tensor_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.46618396, -0.03461919],
       [ 0.6538919 , -0.8194663 ]], dtype=float32)>

<IPython.core.display.Javascript object>

### Shuffle Elements In A Tensor

In [26]:
tensor_1 = tf.constant([[1, 2, 3, 4], 
                        [8, 9, 10, 11], 
                        [1, 3, 5, 7]])

tf.random.shuffle(tensor_1)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  4]], dtype=int32)>

<IPython.core.display.Javascript object>

In [28]:
tf.random.shuffle(tensor_1)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 8,  9, 10, 11],
       [ 1,  2,  3,  4],
       [ 1,  3,  5,  7]], dtype=int32)>

<IPython.core.display.Javascript object>

In [40]:
# To ensure reproducibility, set global and operational level seed
tf.random.set_seed(RANDOM_STATE) # global level seed 
tf.random.shuffle(tensor_1, seed=RANDOM_STATE) # operational level seed

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  4]], dtype=int32)>

<IPython.core.display.Javascript object>

In [35]:
tf.random.shuffle(tensor_1, seed=RANDOM_STATE)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 8,  9, 10, 11],
       [ 1,  3,  5,  7],
       [ 1,  2,  3,  4]], dtype=int32)>

<IPython.core.display.Javascript object>

### Other Ways of Creating Tensors

* tf.ones()
* tf.zeros()

In [41]:
# tf.zeros
tf.zeros(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

<IPython.core.display.Javascript object>

In [42]:
# tf.ones()
tf.ones(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

<IPython.core.display.Javascript object>

### Create Tensors From NumPy Arrays

In [43]:
arr_A = np.arange(1, 17).reshape(2, 2, 4)
tf.constant(arr_A, dtype=tf.float16)

<tf.Tensor: shape=(2, 2, 4), dtype=float16, numpy=
array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]], dtype=float16)>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>