<a href="https://colab.research.google.com/github/chineidu/NLP-Tutorial/blob/main/notebook/03_tensorflow/01_intro_to_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Tutorial

In [1]:
# Standard imports
import numpy as np
import tensorflow as tf


* Intro To Tensors
* Getting info from tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function
* Using GPUs/TPUs with TensorFlow


In [2]:
tf.__version__

'2.11.0'

In [3]:
!python -V

Python 3.8.10


### Create Tensors

In [4]:
# tf.constant
tensor_1 = tf.constant([1, 2, 3, 4]) # Vector
tensor_1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [5]:
tensor_1.shape, tensor_1.ndim

(TensorShape([4]), 1)

In [6]:
tensor_2 = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=tf.float16) # Matrix
tensor_2, tensor_2.shape, tensor_2.ndim

(<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
 array([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], dtype=float16)>, TensorShape([2, 4]), 2)

In [7]:
tensor_3 = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], dtype=tf.float16) # Tensor
tensor_3

<tf.Tensor: shape=(1, 3, 3), dtype=float16, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float16)>

In [8]:
tensor_3.shape, tensor_3.ndim

(TensorShape([1, 3, 3]), 3)

In [9]:
tensor_4 = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                        [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
tensor_4

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

### Creating Tensors Using tf.Variable

In [10]:
# tf.constant
changeable_tensor_1 = tf.Variable([1, 2, 3, 4]) # Vector
changeable_tensor_1

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [11]:
# Change an element in the tensor (Only possible for tensors created using tf.Variable)
changeable_tensor_1[0].assign(-2)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([-2,  2,  3,  4], dtype=int32)>

In [12]:
changeable_tensor_1

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([-2,  2,  3,  4], dtype=int32)>

### Creating Random Tensors

In [13]:
RANDOM_STATE = 123
rng = tf.random.Generator.from_seed(RANDOM_STATE)

random_tensor_1 = rng.uniform(shape=(2, 2), dtype=tf.float16)
random_tensor_1

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[0.8076, 0.793 ],
       [0.4648, 0.2275]], dtype=float16)>

In [14]:
random_tensor_2 = rng.normal(shape=(2,2))
random_tensor_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.46618396, -0.03461919],
       [ 0.6538919 , -0.8194663 ]], dtype=float32)>

### Shuffle Elements In A Tensor

In [15]:
tensor_1 = tf.constant([[1, 2, 3, 4], 
                        [8, 9, 10, 11], 
                        [1, 3, 5, 7]])

tf.random.shuffle(tensor_1)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11],
       [ 1,  3,  5,  7]], dtype=int32)>

In [16]:
tf.random.shuffle(tensor_1)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  4]], dtype=int32)>

In [17]:
# To ensure reproducibility, set global and operational level seed
tf.random.set_seed(RANDOM_STATE) # global level seed 
tf.random.shuffle(tensor_1, seed=RANDOM_STATE) # operational level seed

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  4]], dtype=int32)>

In [18]:
tf.random.shuffle(tensor_1, seed=RANDOM_STATE)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 8,  9, 10, 11],
       [ 1,  3,  5,  7],
       [ 1,  2,  3,  4]], dtype=int32)>

### Other Ways of Creating Tensors

* tf.ones()
* tf.zeros()

In [19]:
# tf.zeros
tf.zeros(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [20]:
# tf.ones()
tf.ones(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### Create Tensors From NumPy Arrays

In [21]:
arr_A = np.arange(1, 17).reshape(2, 2, 4)
tf_arr = tf.constant(arr_A, dtype=tf.float16)
tf_arr

<tf.Tensor: shape=(2, 2, 4), dtype=float16, numpy=
array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]], dtype=float16)>

In [22]:
# Convert a tensor to NumPy array
tf_arr.numpy()

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]], dtype=float16)

### Extracting Info From A Tensor

* array.dtype
* array.shape
* array.ndim
* tf.size(array)
* indexing a tensor

In [23]:
tf_arr.shape, tf_arr.ndim, tf.size(tf_arr)

(TensorShape([2, 2, 4]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=16>)

In [24]:
print(tf_arr)
print(" ====================================================================== ")
print(f"\ndtype: {tf_arr.dtype},\nshape: {tf_arr.shape}, \nnumber of dimensions: {tf_arr.ndim}, \nsize of tensor: {tf.size(tf_arr)}")

tf.Tensor(
[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]], shape=(2, 2, 4), dtype=float16)

dtype: <dtype: 'float16'>,
shape: (2, 2, 4), 
number of dimensions: 3, 
size of tensor: 16


In [25]:
# Rank 4 Tensor
rank_4_tensor = tf.ones((2, 3, 4, 3), dtype=tf.float16)
rank_4_tensor

# Within the Oth axis, we have 2 (smaller arrays)
# Within the 1st axis (i.e the 2 from above), we have 3-D (3, 4, 3)
# Within the 2nd axis (i.e the 3-D from above), we have 4 rows (4, 3)
# Within the 3rd axis (i.e the 4 rows from above), we have 3 columns

<tf.Tensor: shape=(2, 3, 4, 3), dtype=float16, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]], dtype=float16)>

In [26]:
# Oth 
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 3), dtype=float16, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float16)>

In [27]:
arr = np.random.randint(2, 12, size=(2, 3, 4, 3))
rank_4_tensor = tf.constant(arr, dtype=tf.float16)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 3), dtype=float16, numpy=
array([[[[ 7.,  6., 10.],
         [ 3.,  9.,  8.],
         [ 8.,  5.,  5.],
         [ 4.,  5., 10.]],

        [[11.,  8.,  3.],
         [ 9.,  9.,  2.],
         [ 6.,  4.,  9.],
         [ 3.,  5.,  8.]],

        [[ 5.,  8.,  8.],
         [ 7.,  4.,  7.],
         [ 6.,  2.,  6.],
         [ 2.,  8.,  5.]]],


       [[[ 5., 10.,  7.],
         [ 5., 11., 10.],
         [ 5.,  6.,  7.],
         [ 5.,  9.,  3.]],

        [[11.,  8., 10.],
         [ 2.,  6.,  6.],
         [10., 11.,  5.],
         [ 4.,  6.,  5.]],

        [[ 8.,  6.,  2.],
         [11.,  9.,  5.],
         [11.,  5.,  6.],
         [ 6.,  8.,  2.]]]], dtype=float16)>

In [28]:
# 0th index of the 0th axis
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 3), dtype=float16, numpy=
array([[[ 7.,  6., 10.],
        [ 3.,  9.,  8.],
        [ 8.,  5.,  5.],
        [ 4.,  5., 10.]],

       [[11.,  8.,  3.],
        [ 9.,  9.,  2.],
        [ 6.,  4.,  9.],
        [ 3.,  5.,  8.]],

       [[ 5.,  8.,  8.],
        [ 7.,  4.,  7.],
        [ 6.,  2.,  6.],
        [ 2.,  8.,  5.]]], dtype=float16)>

In [29]:
# 1st index of the 0th axis
rank_4_tensor[1]

<tf.Tensor: shape=(3, 4, 3), dtype=float16, numpy=
array([[[ 5., 10.,  7.],
        [ 5., 11., 10.],
        [ 5.,  6.,  7.],
        [ 5.,  9.,  3.]],

       [[11.,  8., 10.],
        [ 2.,  6.,  6.],
        [10., 11.,  5.],
        [ 4.,  6.,  5.]],

       [[ 8.,  6.,  2.],
        [11.,  9.,  5.],
        [11.,  5.,  6.],
        [ 6.,  8.,  2.]]], dtype=float16)>

In [30]:
# 0th index of the 0th axis and 1st index of the 1st axis
rank_4_tensor[0, 1]

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[11.,  8.,  3.],
       [ 9.,  9.,  2.],
       [ 6.,  4.,  9.],
       [ 3.,  5.,  8.]], dtype=float16)>

In [31]:
# 0th index of the 0th axis
rank_4_tensor[0, 1, 0]

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([11.,  8.,  3.], dtype=float16)>

In [32]:
# Extract all the 2nd index from the tensor
rank_4_tensor[:, :, 2]

<tf.Tensor: shape=(2, 3, 3), dtype=float16, numpy=
array([[[ 8.,  5.,  5.],
        [ 6.,  4.,  9.],
        [ 6.,  2.,  6.]],

       [[ 5.,  6.,  7.],
        [10., 11.,  5.],
        [11.,  5.,  6.]]], dtype=float16)>

In [33]:
arr

array([[[[ 7,  6, 10],
         [ 3,  9,  8],
         [ 8,  5,  5],
         [ 4,  5, 10]],

        [[11,  8,  3],
         [ 9,  9,  2],
         [ 6,  4,  9],
         [ 3,  5,  8]],

        [[ 5,  8,  8],
         [ 7,  4,  7],
         [ 6,  2,  6],
         [ 2,  8,  5]]],


       [[[ 5, 10,  7],
         [ 5, 11, 10],
         [ 5,  6,  7],
         [ 5,  9,  3]],

        [[11,  8, 10],
         [ 2,  6,  6],
         [10, 11,  5],
         [ 4,  6,  5]],

        [[ 8,  6,  2],
         [11,  9,  5],
         [11,  5,  6],
         [ 6,  8,  2]]]])

In [34]:
arr_1 = np.arange(4, 22).reshape(2, 3, 3)
arr_1

array([[[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]]])

In [35]:
a = arr_1[0]
a[[0,1,2], [0,1,2]]

array([ 4,  8, 12])

In [36]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 3), dtype=float16, numpy=
array([[[[ 7.,  6., 10.],
         [ 3.,  9.,  8.],
         [ 8.,  5.,  5.],
         [ 4.,  5., 10.]],

        [[11.,  8.,  3.],
         [ 9.,  9.,  2.],
         [ 6.,  4.,  9.],
         [ 3.,  5.,  8.]],

        [[ 5.,  8.,  8.],
         [ 7.,  4.,  7.],
         [ 6.,  2.,  6.],
         [ 2.,  8.,  5.]]],


       [[[ 5., 10.,  7.],
         [ 5., 11., 10.],
         [ 5.,  6.,  7.],
         [ 5.,  9.,  3.]],

        [[11.,  8., 10.],
         [ 2.,  6.,  6.],
         [10., 11.,  5.],
         [ 4.,  6.,  5.]],

        [[ 8.,  6.,  2.],
         [11.,  9.,  5.],
         [11.,  5.,  6.],
         [ 6.,  8.,  2.]]]], dtype=float16)>

In [37]:
# Get the first 2 elements in each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float16, numpy=
array([[[[ 7.,  6.],
         [ 3.,  9.]],

        [[11.,  8.],
         [ 9.,  9.]]],


       [[[ 5., 10.],
         [ 5., 11.]],

        [[11.,  8.],
         [ 2.,  6.]]]], dtype=float16)>

### Add Extra Dimension

* tensor[.., tf.newaxis]
* tf.expand_dims()

```python
tensor[.., tf.newaxis]
tf.expand_dims()
```

In [38]:
tensor_1 = tf.constant([[2, 4], [8, 10]])
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 8, 10]], dtype=int32)>

In [39]:
tensor_1[..., tf.newaxis] # OR tensor_1[:, :, tf.newaxis]

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 2],
        [ 4]],

       [[ 8],
        [10]]], dtype=int32)>

In [40]:
tensor_1[tf.newaxis, ...]

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[ 2,  4],
        [ 8, 10]]], dtype=int32)>

In [41]:
tf.expand_dims(tensor_1, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[ 2,  4],
        [ 8, 10]]], dtype=int32)>

# Adding New Dimensions

* tf.expand_dims()


In [42]:
tf.expand_dims(tensor_1, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[ 2,  4]],

       [[ 8, 10]]], dtype=int32)>

In [43]:
tf.expand_dims(tensor_1, axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 2],
        [ 4]],

       [[ 8],
        [10]]], dtype=int32)>

### Manipulating Tensors With Basic Operations

> Element-wise operations.

* Addition
* Subtraction
* Multiplication
* Division

In [44]:
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 8, 10]], dtype=int32)>

In [45]:
# Addition (Broadcasting)
tensor_1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 14],
       [18, 20]], dtype=int32)>

In [46]:
# Subtraction, Multiplcation (Broadcasting)
tensor_1 - 10, tensor_1 * 10,

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-8, -6],
        [-2,  0]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 20,  40],
        [ 80, 100]], dtype=int32)>)

In [47]:
tf.add(tensor_1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 14],
       [18, 20]], dtype=int32)>

### Matrix Multiplcation

* Check this interactive matrix multiplication [website](https://matrixmultiplication.xyz)

In [48]:
tensor_1 = tf.constant([[1, 2, 3], [5, 6, 7]])
tensor_2 = tf.constant([[-3, 15, 1], [4, 9, 0]])
tensor_1.shape, tensor_2.shape 

(TensorShape([2, 3]), TensorShape([2, 3]))

* The tensors must have equal inner dimensions before dot product can be performed. \
e.g (a, b) . (b, c) \
The result has a shape of (a, b)


In [49]:
# Reshape one of the matrixes before you can perform matrix multiplcation
tf.matmul(tensor_1, tf.transpose(tensor_2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 22],
       [82, 74]], dtype=int32)>

#### You can also reshape one of the tensors into an appropriate shape

In [50]:
# (3, 3) . (2, 3)
tf.matmul(tf.reshape(tensor_1, shape=(3, 2)), tensor_2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  5,  33,   1],
       [ 11,  90,   3],
       [ 10, 153,   6]], dtype=int32)>

In [51]:
print(f"Original tensor: \n{tensor_1}, \nTransposed tensor: \n{tf.transpose(tensor_1)}, \nReshaped tensor: \n{tf.reshape(tensor_1, shape=(3, 2))}")

Original tensor: 
[[1 2 3]
 [5 6 7]], 
Transposed tensor: 
[[1 5]
 [2 6]
 [3 7]], 
Reshaped tensor: 
[[1 2]
 [3 5]
 [6 7]]


### Changing Data Types

* tf.cast(tensor, dtype=tf.datatype)

In [52]:
A = tf.constant([[1., 3.], [8., -9.]])
B = tf.constant([[-4., 3.], [2., 9.]])

A, B

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 1.,  3.],
        [ 8., -9.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-4.,  3.],
        [ 2.,  9.]], dtype=float32)>)

In [53]:
tf.cast(A, dtype=tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 1.,  3.],
       [ 8., -9.]], dtype=float16)>

### Aggregating Tensors

* Min
* Max
* Mean
* Sum

In [54]:
A

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  3.],
       [ 8., -9.]], dtype=float32)>

In [55]:
tf.math.reduce_min(A)

<tf.Tensor: shape=(), dtype=float32, numpy=-9.0>

In [56]:
tf.math.reduce_min(A).numpy()

-9.0

In [57]:
tf.math.reduce_max(A), tf.math.reduce_sum(A)

(<tf.Tensor: shape=(), dtype=float32, numpy=8.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.0>)

In [58]:
tf.math.reduce_variance(A).numpy()

38.1875

In [59]:
tf.math.reduce_std(A).numpy()

6.1796036

### Positional Maximum

* tf.argmax()

In [60]:
tensor_1 = tf.constant(value=np.random.uniform(low=0, high=1, size=(12,)))

tensor_1

<tf.Tensor: shape=(12,), dtype=float64, numpy=
array([0.02049341, 0.5037543 , 0.1337863 , 0.71391527, 0.95212091,
       0.40744755, 0.3938284 , 0.34887765, 0.37470817, 0.67591657,
       0.50229032, 0.63163712])>

In [61]:
# Find the argmax of tensor_1
print(tf.argmax(tensor_1).numpy())

tensor_1[tf.argmax(tensor_1)]

4


<tf.Tensor: shape=(), dtype=float64, numpy=0.9521209077507361>

In [62]:
# Verify!
tf.math.reduce_max(tensor_1)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9521209077507361>

In [63]:
# Positional Minimum (tf.argmin)
tf.argmin(tensor_1).numpy()

0

### Removing All Dimensions (Squeezing)

> This removes dimensions of size `1` from the shape of a tensor. e.g a tensor with shape: (1, 1, 5) becomes (5)

* tf.squeeze()

In [64]:
tensor_2 = tf.constant(value=np.random.uniform(low=0, high=1, size=(1, 1, 1, 12)))

tensor_2

<tf.Tensor: shape=(1, 1, 1, 12), dtype=float64, numpy=
array([[[[0.80439856, 0.4256437 , 0.9826591 , 0.50408363, 0.08583492,
          0.22746205, 0.46155544, 0.7352592 , 0.83785513, 0.16663632,
          0.3701493 , 0.47052257]]]])>

In [65]:
tf.size(tensor_2), tensor_2.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=12>, TensorShape([1, 1, 1, 12]))

In [66]:
squeezed_tensor = tf.squeeze(tensor_2)
squeezed_tensor.shape

TensorShape([12])

### One Hot Encoding

In [67]:
#         "Nigeria",  "Germany",  "USA",  "Canada"
my_list = [  0,           1,        2,       3]


# One-hot encode the list
tf.one_hot(my_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [68]:
## Square a tensor
T = tf.range(1, 10)
tf.square(T)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [69]:
tf.math.square(T)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [70]:
# Square root
# Only floats are allowed
T = tf.range(10)
tf.cast(T, dtype=tf.float16)

<tf.Tensor: shape=(10,), dtype=float16, numpy=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)>

In [71]:
tf.math.sqrt(tf.cast(T, dtype=tf.float16))

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([0.   , 1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828,
       3.   ], dtype=float16)>

In [72]:
# Find the log
tf.math.log(tf.cast(T, dtype=tf.float16))

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([  -inf, 0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 ,
       2.08  , 2.197 ], dtype=float16)>

### Working With NumPy

In [73]:
T = tf.constant(np.random.uniform(size=10))
T

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.39399763, 0.02722808, 0.48163581, 0.94645505, 0.46077315,
       0.89774822, 0.9616575 , 0.29930087, 0.6600206 , 0.61155561])>

In [74]:
# Convert back to NumPy
T.numpy()

array([0.39399763, 0.02722808, 0.48163581, 0.94645505, 0.46077315,
       0.89774822, 0.9616575 , 0.29930087, 0.6600206 , 0.61155561])

In [75]:
# NumPy and TensorFlow have slightly different datatypes
H = tf.range(10)
T = tf.constant(np.arange(10))

H.dtype, T.dtype

(tf.int32, tf.int64)

In [76]:
# Check The Physical Devices
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]