<a href="https://colab.research.google.com/github/chineidu/NLP-Tutorial/blob/main/notebook/03_tensorflow/01_intro_to_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Tutorial

In [1]:
!pip install nb_black

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 51.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 11.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 50.1 MB/s eta 0:00:00
  Created wheel for nb_black: filename=nb_black-1.0.7-py3-none-any.whl size=5298 sha256=ce1dd39c05e251a3ebb036c2122fd21c346c9d1a0e35000d7b6f35e93c4d78c2
  Stored in directory: /root/.cache/pip/wheels/a6/5e/1e/a15614d6ea220d070043db3b650d73a8b4938aefd520496c11
Successfully built nb_black
  Attempting uninstall: click
    Found existing installation: click 7.1.2
    Uninstalling click-7.1.2:
      Successfully uninstalled click-7.1.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 1.1.

In [3]:
# Standard imports
import numpy as np
import tensorflow as tf

# Black code formatter (Optional)
# %load_ext lab_black
%load_ext nb_black

* Intro To Tensors
* Getting info from tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function
* Using GPUs/TPUs with TensorFlow


In [4]:
tf.__version__

'2.11.0'

In [5]:
!python -V

Python 3.8.10


### Create Tensors

In [6]:
# tf.constant
tensor_1 = tf.constant([1,2,3,4]) # Vector
tensor_1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [7]:
tensor_1.shape, tensor_1.ndim

(TensorShape([4]), 1)

In [8]:
tensor_2 = tf.constant([[1,2,3,4], [5,6,7,8]], dtype=tf.float16) # Matrix
tensor_2, tensor_2.shape, tensor_2.ndim

(<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
 array([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], dtype=float16)>, TensorShape([2, 4]), 2)

In [9]:
tensor_3 = tf.constant([[[1,2,3], [4,5,6], [7, 8, 9]]], dtype=tf.float16) # Tensor
tensor_3

<tf.Tensor: shape=(1, 3, 3), dtype=float16, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float16)>

In [10]:
tensor_3.shape, tensor_3.ndim

(TensorShape([1, 3, 3]), 3)

In [10]:
tensor_4 = tf.constant([[[1,2,3], [4,5,6]]])

# 2, 3, 3